from .methods import (
    CNext, CNextv2, CNext3d,
    CROP, CROP3d,
    DeepONet, DeepONetv2, DeepONet_deepxde, DeepONet_deepxde3d, DeepONet_deepxdeU,
    DPOT, DPOT3d,
    FactFormer, FactFormerv2,
    FFNO, FFNO3d, FFNOU,
    FNO, FNO3d,
    GNOT,
    ONO,
    Transolver, Transolver3d, TransolverU,
    UNO, UNOv2, UNO3d,
    PointNet,
    MGN,
    GAT, GraphSAGE, GraphUNet,
    PhysicsTransformer, LSM
)

model_dict = {
    'CNext': CNext,
    'CNextv2': CNextv2,
    'CNext3d': CNext3d,
    'CROP': CROP,
    'CROP3d': CROP3d,
    'DeepONet': DeepONet,
    'DeepONetv2': DeepONetv2,
    'DeepONet_deepxde': DeepONet_deepxde,
    'DeepONet_deepxde3d': DeepONet_deepxde3d,
    'DeepONet_deepxdeU': DeepONet_deepxdeU,
    'DPOT': DPOT,
    'DPOT3d': DPOT3d,
    'FactFormer': FactFormer,
    'FactFormerv2': FactFormerv2,
    'FFNO': FFNO,
    'FFNO3d': FFNO3d,
    'FNO': FNO,
    'FNO3d': FNO3d,
    'FFNOU': FFNOU,
    'GNOT': GNOT,
    'ONO': ONO,
    'Transolver': Transolver,
    'Transolver3d': Transolver3d,
    'TransolverU': TransolverU,
    'UNO': UNO,
    'UNOv2': UNOv2,
    'UNO3d': UNO3d,
    'PointNet': PointNet,
    'MGN': MGN,
    'GAT': GAT,
    'GraphSAGE': GraphSAGE,
    'GraphUNet': GraphUNet,
    'PhysicsTransformer': PhysicsTransformer,
    'LSM': LSM,
}

__all__ = ['model_dict']